# Learn more: https://trunkrs.dev/configuration/#trunk-toml

[build]
# The index HTML file to drive the bundling process.
target = "index.html"

[watch]
watch = [
    "src",
    "static/",
    "index.html"
]