name: Deployer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.79.0
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: deploy-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: deploy-${{ runner.os }}-cargo-
      - name: Install trunk
        run: cargo install --locked trunk
      - name: Build
        run: trunk build --release --public-url ${{ github.event.repository.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: ./dist
  deploy-to-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create artifact dir
        run: mkdir ./dist
      - name: Acquire artifact
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: ./dist
      - name: Push to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/